# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_push_customers_docker_image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
       DOCKER_USER: ${{secrets.DOCKER_USER}}
       DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
       APP_VERSION: 0.1.0-${{github.run_id}}       
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Login Docker
      - name: Docker login       
        run: |
          docker login -u ${{env.DOCKER_USER}} -p ${{env.DOCKER_PASSWORD}}
      
      # Build Docker image
      - name: Build Docker image
        run: docker build -f nolt-customer-orders/Dockerfile . --tag ${{env.DOCKER_USER}}/nolt-customers:${{env.APP_VERSION}}
      
      # Push Docker image to repository
      - name: Push Docker image
        run: docker push ${{env.DOCKER_USER}}/nolt-customers:${{env.APP_VERSION}}
